
-- BUSCANDO PESSOAS UTILIZANDO A CONDIÇÕES LIKE e NOT LIKE

--LIKE 'A%'  = VAI BUSCAR TODOS OS NOMES COM A LETRA A NO COMEÇO
--LIKE '%A%' = VAI BUSCAR TODOS OS NOMES COM A LETRA A
--LIKE '%A'  = VAI BUSCAR TODOS OS NOMES COM A LETRA A NO FINAL

SELECT ID_Pessoa
      ,NM_Pessoa
FROM dbo.Pessoas
WHERE NM_Pessoa LIKE '%Lucas%'

-- NOT LIKE 'A%'  = NÃO VAI BUSCAR OS NOMES COM A LETRA A NO COMEÇO
-- NOT LIKE '%A%' = NÃO VAI BUSCAR OS NOMES COM A LETRA A
-- NOT LIKE '%A'  = NÃO VAI BUSCAR OS NOMES COM A LETRA A NO FINAL


SELECT ID_Pessoa
      ,NM_Pessoa
FROM dbo.Pessoas
WHERE NM_Pessoa NOT LIKE '%Lucas%'
