
-- BUSCANDO PESSOAS UTILIZANDO A CONDIÇÃO BETWEEN

-- BETWEEN = VAI TRAZER TUDO QUE ESTÁ NO PONTO INICIAL, FINAL E ENTRE OS AMBOS
-- RESUMIDAMENTE VAI TRAZER 1,2 E 3.
SELECT ID_Pessoa
FROM dbo.Pessoas
WHERE ID_Pessoa BETWEEN 1 AND 3 

