
-- UTILIZANDO UNION E UNION ALL PARA COMBINAR CONSULTAS DIFERENTES
-- UNION ALL  = COMBINA OS RESULTADO DAS DUAS CONSULTAS
SELECT NM_Pessoa 
FROM dbo.Pessoas
WHERE NM_Pessoa = 'José da Silva'
UNION ALL
SELECT NM_Pessoa 
FROM dbo.Pessoas
WHERE NM_Pessoa = 'Lucas Casarotti'

-- UNION  = COMBINA OS RESULTADO DAS DUAS CONSULTAS, PORÉM EXECUTA O SELECT DISTINCT NO RESULT SET
SELECT NM_Pessoa 
FROM dbo.Pessoas
WHERE NM_Pessoa = 'José da Silva'
UNION
SELECT NM_Pessoa 
FROM dbo.Pessoas
WHERE NM_Pessoa = 'Lucas Casarotti'