
-- FUNÇÕES COUNT, SUM, MIN E MAX

-- COUNT = VAI SOMAR A QUANTIDADE DE REGISTROS
SELECT COUNT(VL_Salario)
FROM dbo.Cargos

-- SUM   = VAI SOMAR O VALOR DE TODOS REGISTROS
SELECT SUM(VL_Salario)
FROM dbo.Cargos

-- MIN   = VAI MOSTRAR O VALOR MÍNIMO
SELECT MIN(VL_Salario)
FROM dbo.Cargos

-- MAX   = VAI MOSTRAR O VALOR MÁXIMO
SELECT MAX(VL_Salario)
FROM dbo.Cargos
