
-- BUSCANDO AS PESSOAS QUE TENHA A COLUNA NOME DIFERENTE, CASO TENHA DUAS PESSOAS COM O MESMO NOME SERÁ EXIBIDO APENAS UMA VEZ

SELECT DISTINCT
       NM_Pessoa 
FROM dbo.Pessoas

-- PODE SER UTILIZADO O DISTINCT PARA MAIS DE UMA COLUNA, PORÉM PARA QUE FUNCIONE AMBAS AS COLUNAS DEVEM SER IGUAIS, CASO CONTRÁRIO MOSTRARÁ OS DEMAIS REGISTROS
SELECT DISTINCT
       NM_Pessoa 
      ,DT_Nascimento
	  ,CD_Inscricao_Nacional
FROM dbo.Pessoas
WHERE NM_Pessoa = 'Lucas Casarotti'

