
-- FUNÇÕES DE AGREGAÇÃO

-- COUNT = UTILIZADA PARA SOMAR A QUANTIDADE DE REGISTROS DA COLUNA
SELECT COUNT(VL_Salario)
FROM dbo.Cargos

-- SUM   = UTILIZADA PARA SOMAR O VALOR DE TODOS REGISTROS DA COLUNA NA TABELA
SELECT SUM(VL_Salario)
FROM dbo.Cargos

-- MIN   = UTILIZADA PARA MOSTRAR O VALOR MÍNIMO DA COLUNA
SELECT MIN(VL_Salario)
FROM dbo.Cargos

-- MAX   = UTILIZADA PARA MOSTRAR O VALOR MÁXIMO DA COLUNA
SELECT MAX(VL_Salario)
FROM dbo.Cargos
