
-- APAGANDO UMA COLUNA DESNECESSÁRIA DA TABELA TURMAS
-- PARA APAGAR CAMPO DO TIPO FOREIGN KEY PRIMEIRO É PRECISO APAGAR A CONSTRANT
-- ENTÃO PRECISA APAGAR A CONSTRANT E LOGO EM SEGUIDA O CAMPO QUE TINHA A CONSTRANT

ALTER TABLE dbo.Turmas
DROP CONSTRAINT fk_Alunos;

ALTER TABLE dbo.Turmas
DROP COLUMN ID_Aluno;

ALTER TABLE dbo.Turmas
DROP COLUMN Valor_Turma;

ALTER TABLE dbo.Turmas
DROP COLUMN Desconto;
