
-- ALTERANDO APENAS UM REGISTRO UTILIZANDO A CLAUSULA WHERE
UPDATE dbo.Alunos SET Nome = 'Lucas Matheus' WHERE ID_Aluno = 1;

-- PODEMOS UTILIZAR A CLAUSE WHERE PARA TODAS AS COLUNAS DO BANCO
-- POREM SERA ALTERADO TODOS OS DADOS QUE TIVEREM A MESMA CONDIÇÃO DA CLAUSULA WHERE
-- ALTERANDO TODOS OS REGISTRO QUE TIVEREM O NOME IGUAL
UPDATE dbo.Alunos SET Nome = 'Lucas Casarotti' WHERE Nome = 'Lucas Matheus';

-- ALTERANDO TODOS OS REGISTRO
UPDATE dbo.Alunos SET Nome = 'Lucas Matheus Casarotti';