-- UTILIZANDO A FUNÇÃO COUNT

-- CONTANDO O TOTAL DE CURSOS
SELECT COUNT(ID_Curso) AS 'Total de cursos' FROM Cursos

-- CONTANDO O TOTAL DE ALUNOS
SELECT COUNT (ID_Aluno) AS 'Total de alunos' FROM Alunos

-- CONTANDO O TOTAL DE TURMAS
SELECT COUNT (ID_Turma) AS 'Total de turmas' FROM Turmas

-- PODEMOS TAMBÉM UTILIZAR A CONDIÇÃO WHERE
-- COUNTANDO O TOTAL DE ALUNOS DO SEXO MASCULINO
SELECT COUNT(ID_Aluno)  FROM Alunos
WHERE Sexo = 'M'